# Generated by Django 4.0 on 2022-02-08 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_percent',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.FloatField(max_length=10),
        ),
    ]
